name: Profile Summary Cards
on:
  schedule: [{ cron: "0 6 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: Akkikens
          THEME: transparent            # choose any theme you like
          UTC_OFFSET: 0
          # OUTPUT_PATH defaults to profile-summary-card-output
