name: Summary Cards
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  cards:
    runs-on: ubuntu-latest
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: Akkikens
          # optional: set UTC offset for time-of-day cards
          UTC_OFFSET: 5.5
