name: Profile Metrics
on:
  schedule:
    - cron: "0 */12 * * *"   # twice a day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Auth
          token: ${{ secrets.METRICS_TOKEN }}
          user: Akkikens
          config_timezone: Asia/Kolkata

          # Base template & sections
          template: classic
          base: header, activity, community, repositories, metadata

          # Recent activity (shows merged PRs, reviews, comments, etc.)
          plugin_activity: yes
          plugin_activity_limit: 10
          plugin_activity_days: 14
          plugin_activity_filter: issue, pr, review, ref/create, ref/delete

          # Follow-up: open/closed/merged PRs & issues (user + repos)
          plugin_followup: yes
          plugin_followup_sections: user, repositories

          # Lines added/removed
          plugin_lines: yes

          # Languages (in-depth)
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: percentage

          # Fun but useful extras
          plugin_achievements: yes
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14

          # Output file
          filename: metrics.svg
