name: GitHub Metrics
on:
  schedule: [{ cron: "25 3 * * *" }]   # daily @ 03:25 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}   # classic PAT (repo + read:user)
          user: Akkikens
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          output_action: commit
          committer_message: "chore: update metrics"
          filename: metrics.svg                 # → commits /metrics.svg to repo root
